version: '3.8'
services:
  webserver:
    build:
      dockerfile: ./nginx/Dockerfile
    ports:
      - 8021:80
    volumes:
      - ./WebAPI:/var/www/html

  php:
    build:
      dockerfile: ./php/Dockerfile
    expose:
      - 9000
    volumes:
      - ./WebAPI:/var/www/html

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: RootP@ssw0rd
      MYSQL_DATABASE: deploymentcenter
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: UserP@ssw0rd
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./Docker/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: RootP@ssw0rd
